#
# development
#

image: php:7.2.3

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update
          - apt-get install -y unzip          
          - apt-get install -y git
          - apt-get install -y libxslt1-dev
          - docker-php-ext-install -j$(nproc) xsl
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer update
          - chmod +x vendor/phpunit/phpunit/phpunit
          - chmod +x vendor/bin/phpunit
          - ./vendor/bin/phing -f ./build.xml tests